### ISSUE TITLE
hello any example on how to project mixamo fbx mesh on image?

### ISSUE THREAD

**Issue by lucasjinreal** [ptrvilya/blendify#1]
The reason why need this is for retarget smpl motion to mixamo and render image, is blendify have any example show this?

**Comment by vguzov** [comment]
Hi,
Sorry, can't suggest anything here: dealing with mesh loading/generating/rigging is out of scope for Blendify, it only renders stuff:)

**Comment by lucasjinreal** [comment]
@vguzov I think what your said is mostly blender did it, what I want ask is how to using blendify 's Hight level API more easily to do this. And I think this is a common demands from user. Any prompts/docs would be very appreciated if it has. 

Really hoping for this can replace pyrender old and problematic lib. (if speed can faster would be much more valuable)

**Comment by vguzov** [comment]
Closed as discussion moved to issue #4.
