### ISSUE TITLE
UV map leakage

### ISSUE THREAD

**Issue by isarandi** [ptrvilya/blendify#10]
If you replace a mesh's colors with `update_colors()` with a new `TextureColors` several times, a warning appears that only 8 UV maps are allowed. Digging in the code, I think UV maps should be cleaned up in `_blender_clear_colors()`

The UV map is created [here](https://github.com/ptrvilya/blendify/blob/17e3cf31f5f775b316d1254a46b2ac1e01f9dd62/blendify/renderables/mesh.py#L122)

A possible solution would be to override `_blender_create_colors` in `Mesh` as

```python
    def _blender_clear_colors(self):
        """Clears Blender color node and erases node constructor
        """
        for uv_layer in self._blender_mesh.uv_layers.values():
            self._blender_mesh.uv_layers.remove(uv_layer)
        super()._blender_clear_colors()
```

This makes the warning go away, and the renders still look good.

**Comment by vguzov** [comment]
Solved by https://github.com/ptrvilya/blendify/pull/11, thank you for the pull request!
